<?php
/**
 * MpsAgreement
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Reepay\Model;

use \ArrayAccess;

/**
 * MpsAgreement Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Reepay
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MpsAgreement implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'MpsAgreement';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'currencies' => 'string[]',
        'country' => 'string',
        'shop_name' => 'string',
        'merchant_vat' => 'string',
        'provider_id' => 'string',
        'authorization_url' => 'string',
        'async_one_off' => 'bool'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'currencies' => 'currencies',
        'country' => 'country',
        'shop_name' => 'shop_name',
        'merchant_vat' => 'merchant_vat',
        'provider_id' => 'provider_id',
        'authorization_url' => 'authorization_url',
        'async_one_off' => 'async_one_off'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'currencies' => 'setCurrencies',
        'country' => 'setCountry',
        'shop_name' => 'setShopName',
        'merchant_vat' => 'setMerchantVat',
        'provider_id' => 'setProviderId',
        'authorization_url' => 'setAuthorizationUrl',
        'async_one_off' => 'setAsyncOneOff'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'currencies' => 'getCurrencies',
        'country' => 'getCountry',
        'shop_name' => 'getShopName',
        'merchant_vat' => 'getMerchantVat',
        'provider_id' => 'getProviderId',
        'authorization_url' => 'getAuthorizationUrl',
        'async_one_off' => 'getAsyncOneOff'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['currencies'] = isset($data['currencies']) ? $data['currencies'] : null;
        $this->container['country'] = isset($data['country']) ? $data['country'] : null;
        $this->container['shop_name'] = isset($data['shop_name']) ? $data['shop_name'] : null;
        $this->container['merchant_vat'] = isset($data['merchant_vat']) ? $data['merchant_vat'] : null;
        $this->container['provider_id'] = isset($data['provider_id']) ? $data['provider_id'] : null;
        $this->container['authorization_url'] = isset($data['authorization_url']) ? $data['authorization_url'] : null;
        $this->container['async_one_off'] = isset($data['async_one_off']) ? $data['async_one_off'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['currencies'] === null) {
            $invalid_properties[] = "'currencies' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['currencies'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets currencies
     * @return string[]
     */
    public function getCurrencies()
    {
        return $this->container['currencies'];
    }

    /**
     * Sets currencies
     * @param string[] $currencies Set of currencies supported by agreement. Each currency in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) three letter alpha code.
     * @return $this
     */
    public function setCurrencies($currencies)
    {
        $this->container['currencies'] = $currencies;

        return $this;
    }

    /**
     * Gets country
     * @return string
     */
    public function getCountry()
    {
        return $this->container['country'];
    }

    /**
     * Sets country
     * @param string $country
     * @return $this
     */
    public function setCountry($country)
    {
        $this->container['country'] = $country;

        return $this;
    }

    /**
     * Gets shop_name
     * @return string
     */
    public function getShopName()
    {
        return $this->container['shop_name'];
    }

    /**
     * Sets shop_name
     * @param string $shop_name
     * @return $this
     */
    public function setShopName($shop_name)
    {
        $this->container['shop_name'] = $shop_name;

        return $this;
    }

    /**
     * Gets merchant_vat
     * @return string
     */
    public function getMerchantVat()
    {
        return $this->container['merchant_vat'];
    }

    /**
     * Sets merchant_vat
     * @param string $merchant_vat
     * @return $this
     */
    public function setMerchantVat($merchant_vat)
    {
        $this->container['merchant_vat'] = $merchant_vat;

        return $this;
    }

    /**
     * Gets provider_id
     * @return string
     */
    public function getProviderId()
    {
        return $this->container['provider_id'];
    }

    /**
     * Sets provider_id
     * @param string $provider_id
     * @return $this
     */
    public function setProviderId($provider_id)
    {
        $this->container['provider_id'] = $provider_id;

        return $this;
    }

    /**
     * Gets authorization_url
     * @return string
     */
    public function getAuthorizationUrl()
    {
        return $this->container['authorization_url'];
    }

    /**
     * Sets authorization_url
     * @param string $authorization_url
     * @return $this
     */
    public function setAuthorizationUrl($authorization_url)
    {
        $this->container['authorization_url'] = $authorization_url;

        return $this;
    }

    /**
     * Gets async_one_off
     * @return bool
     */
    public function getAsyncOneOff()
    {
        return $this->container['async_one_off'];
    }

    /**
     * Sets async_one_off
     * @param bool $async_one_off
     * @return $this
     */
    public function setAsyncOneOff($async_one_off)
    {
        $this->container['async_one_off'] = $async_one_off;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Reepay\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Reepay\ObjectSerializer::sanitizeForSerialization($this));
    }
}


