<?php
/**
 * ChargeTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * ChargeTest Class Doc Comment
 *
 * @category    Class
 * @description Charge
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChargeTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Charge"
     */
    public function testCharge()
    {
    }

    /**
     * Test attribute "handle"
     */
    public function testPropertyHandle()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "authorized"
     */
    public function testPropertyAuthorized()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "cancelled"
     */
    public function testPropertyCancelled()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "transaction"
     */
    public function testPropertyTransaction()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "processing"
     */
    public function testPropertyProcessing()
    {
    }

    /**
     * Test attribute "source"
     */
    public function testPropertySource()
    {
    }

    /**
     * Test attribute "orderLines"
     */
    public function testPropertyOrderLines()
    {
    }

    /**
     * Test attribute "refundedAmount"
     */
    public function testPropertyRefundedAmount()
    {
    }

    /**
     * Test attribute "authorizedAmount"
     */
    public function testPropertyAuthorizedAmount()
    {
    }

    /**
     * Test attribute "errorState"
     */
    public function testPropertyErrorState()
    {
    }

    /**
     * Test attribute "recurringPaymentMethod"
     */
    public function testPropertyRecurringPaymentMethod()
    {
    }

    /**
     * Test attribute "billingAddress"
     */
    public function testPropertyBillingAddress()
    {
    }

    /**
     * Test attribute "shippingAddress"
     */
    public function testPropertyShippingAddress()
    {
    }

    /**
     * Test attribute "paymentContext"
     */
    public function testPropertyPaymentContext()
    {
    }
}
