<?php
/**
 * ChargeSourceTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * ChargeSourceTest Class Doc Comment
 *
 * @category    Class
 * @description ChargeSource
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ChargeSourceTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ChargeSource"
     */
    public function testChargeSource()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "card"
     */
    public function testPropertyCard()
    {
    }

    /**
     * Test attribute "mps"
     */
    public function testPropertyMps()
    {
    }

    /**
     * Test attribute "fingerprint"
     */
    public function testPropertyFingerprint()
    {
    }

    /**
     * Test attribute "provider"
     */
    public function testPropertyProvider()
    {
    }

    /**
     * Test attribute "vippsRecurring"
     */
    public function testPropertyVippsRecurring()
    {
    }

    /**
     * Test attribute "authTransaction"
     */
    public function testPropertyAuthTransaction()
    {
    }

    /**
     * Test attribute "cardType"
     */
    public function testPropertyCardType()
    {
    }

    /**
     * Test attribute "transactionCardType"
     */
    public function testPropertyTransactionCardType()
    {
    }

    /**
     * Test attribute "expDate"
     */
    public function testPropertyExpDate()
    {
    }

    /**
     * Test attribute "maskedCard"
     */
    public function testPropertyMaskedCard()
    {
    }

    /**
     * Test attribute "cardCountry"
     */
    public function testPropertyCardCountry()
    {
    }

    /**
     * Test attribute "strongAuthenticationStatus"
     */
    public function testPropertyStrongAuthenticationStatus()
    {
    }

    /**
     * Test attribute "threeDSecureStatus"
     */
    public function testPropertyThreeDSecureStatus()
    {
    }

    /**
     * Test attribute "riskRule"
     */
    public function testPropertyRiskRule()
    {
    }

    /**
     * Test attribute "acquirerCode"
     */
    public function testPropertyAcquirerCode()
    {
    }

    /**
     * Test attribute "acquirerMessage"
     */
    public function testPropertyAcquirerMessage()
    {
    }

    /**
     * Test attribute "acquirerReference"
     */
    public function testPropertyAcquirerReference()
    {
    }

    /**
     * Test attribute "textOnStatement"
     */
    public function testPropertyTextOnStatement()
    {
    }

    /**
     * Test attribute "surchargeFee"
     */
    public function testPropertySurchargeFee()
    {
    }
}
