<?php
/**
 * DiscountSettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * DiscountSettingsTest Class Doc Comment
 *
 * @category    Class
 * @description DiscountSettings
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DiscountSettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "DiscountSettings"
     */
    public function testDiscountSettings()
    {
    }

    /**
     * Test attribute "discountApplyOrder"
     */
    public function testPropertyDiscountApplyOrder()
    {
    }

    /**
     * Test attribute "discountPercentageApply"
     */
    public function testPropertyDiscountPercentageApply()
    {
    }

    /**
     * Test attribute "multipleAllowed"
     */
    public function testPropertyMultipleAllowed()
    {
    }
}
