<?php
/**
 * TokenRequestorRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * TokenRequestorRequestTest Class Doc Comment
 *
 * @category    Class
 * @description TokenRequestorRequest
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TokenRequestorRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TokenRequestorRequest"
     */
    public function testTokenRequestorRequest()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
    }

    /**
     * Test attribute "test"
     */
    public function testPropertyTest()
    {
    }

    /**
     * Test attribute "company_primary_legal_name"
     */
    public function testPropertyCompanyPrimaryLegalName()
    {
    }

    /**
     * Test attribute "primary_contact_email"
     */
    public function testPropertyPrimaryContactEmail()
    {
    }

    /**
     * Test attribute "company_country_code"
     */
    public function testPropertyCompanyCountryCode()
    {
    }

    /**
     * Test attribute "company_city"
     */
    public function testPropertyCompanyCity()
    {
    }

    /**
     * Test attribute "primary_website_url"
     */
    public function testPropertyPrimaryWebsiteUrl()
    {
    }

    /**
     * Test attribute "card_scheme"
     */
    public function testPropertyCardScheme()
    {
    }
}
