<?php
/**
 * TransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * TransactionTest Class Doc Comment
 *
 * @category    Class
 * @description Transaction
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Transaction"
     */
    public function testTransaction()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "state"
     */
    public function testPropertyState()
    {
    }

    /**
     * Test attribute "invoice"
     */
    public function testPropertyInvoice()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "amount"
     */
    public function testPropertyAmount()
    {
    }

    /**
     * Test attribute "settled"
     */
    public function testPropertySettled()
    {
    }

    /**
     * Test attribute "authorized"
     */
    public function testPropertyAuthorized()
    {
    }

    /**
     * Test attribute "failed"
     */
    public function testPropertyFailed()
    {
    }

    /**
     * Test attribute "refunded"
     */
    public function testPropertyRefunded()
    {
    }

    /**
     * Test attribute "created"
     */
    public function testPropertyCreated()
    {
    }

    /**
     * Test attribute "paymentType"
     */
    public function testPropertyPaymentType()
    {
    }

    /**
     * Test attribute "cardTransaction"
     */
    public function testPropertyCardTransaction()
    {
    }

    /**
     * Test attribute "mpoTransaction"
     */
    public function testPropertyMpoTransaction()
    {
    }

    /**
     * Test attribute "vippsTransaction"
     */
    public function testPropertyVippsTransaction()
    {
    }

    /**
     * Test attribute "applepayTransaction"
     */
    public function testPropertyApplepayTransaction()
    {
    }

    /**
     * Test attribute "googlepayTransaction"
     */
    public function testPropertyGooglepayTransaction()
    {
    }

    /**
     * Test attribute "manualTransaction"
     */
    public function testPropertyManualTransaction()
    {
    }

    /**
     * Test attribute "viabillTransaction"
     */
    public function testPropertyViabillTransaction()
    {
    }

    /**
     * Test attribute "anydayTransaction"
     */
    public function testPropertyAnydayTransaction()
    {
    }

    /**
     * Test attribute "resursTransaction"
     */
    public function testPropertyResursTransaction()
    {
    }

    /**
     * Test attribute "klarnaTransaction"
     */
    public function testPropertyKlarnaTransaction()
    {
    }

    /**
     * Test attribute "swishTransaction"
     */
    public function testPropertySwishTransaction()
    {
    }

    /**
     * Test attribute "paypalTransaction"
     */
    public function testPropertyPaypalTransaction()
    {
    }

    /**
     * Test attribute "bancontactTransaction"
     */
    public function testPropertyBancontactTransaction()
    {
    }

    /**
     * Test attribute "blikTransaction"
     */
    public function testPropertyBlikTransaction()
    {
    }

    /**
     * Test attribute "giropayTransaction"
     */
    public function testPropertyGiropayTransaction()
    {
    }

    /**
     * Test attribute "idealTransaction"
     */
    public function testPropertyIdealTransaction()
    {
    }

    /**
     * Test attribute "p24Transaction"
     */
    public function testPropertyP24Transaction()
    {
    }

    /**
     * Test attribute "sepaTransaction"
     */
    public function testPropertySepaTransaction()
    {
    }

    /**
     * Test attribute "verkkopankkiTransaction"
     */
    public function testPropertyVerkkopankkiTransaction()
    {
    }

    /**
     * Test attribute "mpsTransaction"
     */
    public function testPropertyMpsTransaction()
    {
    }

    /**
     * Test attribute "paymentContext"
     */
    public function testPropertyPaymentContext()
    {
    }
}
