<?php
/**
 * UpdateCardGatewayAgreementTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * UpdateCardGatewayAgreementTest Class Doc Comment
 *
 * @category    Class */
// * @description UpdateCardGatewayAgreement
/**
 * @package     Reepay
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UpdateCardGatewayAgreementTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UpdateCardGatewayAgreement"
     */
    public function testUpdateCardGatewayAgreement()
    {

    }

    /**
     * Test attribute "currencies"
     */
    public function testPropertyCurrencies()
    {

    }

    /**
     * Test attribute "surcharge"
     */
    public function testPropertySurcharge()
    {

    }

    /**
     * Test attribute "card_types"
     */
    public function testPropertyCardTypes()
    {

    }

    /**
     * Test attribute "payment_types"
     */
    public function testPropertyPaymentTypes()
    {

    }

    /**
     * Test attribute "provider_settings"
     */
    public function testPropertyProviderSettings()
    {

    }

    /**
     * Test attribute "fee_configuration"
     */
    public function testPropertyFeeConfiguration()
    {

    }

    /**
     * Test attribute "threed_secure"
     */
    public function testPropertyThreedSecure()
    {

    }

    /**
     * Test attribute "threed_secure_recurring"
     */
    public function testPropertyThreedSecureRecurring()
    {

    }

    /**
     * Test attribute "secured_by_nets"
     */
    public function testPropertySecuredByNets()
    {

    }

    /**
     * Test attribute "secured_by_nets_recurring"
     */
    public function testPropertySecuredByNetsRecurring()
    {

    }

    /**
     * Test attribute "default_require_sca"
     */
    public function testPropertyDefaultRequireSca()
    {

    }

    /**
     * Test attribute "disallow_threed_secure_attempted"
     */
    public function testPropertyDisallowThreedSecureAttempted()
    {

    }

    /**
     * Test attribute "three_d_secure_version"
     */
    public function testPropertyThreeDSecureVersion()
    {

    }

}
