<?php
/**
 * VerkkopankkiTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * VerkkopankkiTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description VerkkopankkiTransaction
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class VerkkopankkiTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VerkkopankkiTransaction"
     */
    public function testVerkkopankkiTransaction()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "ref_transaction"
     */
    public function testPropertyRefTransaction()
    {
    }

    /**
     * Test attribute "error_state"
     */
    public function testPropertyErrorState()
    {
    }

    /**
     * Test attribute "acquirer_message"
     */
    public function testPropertyAcquirerMessage()
    {
    }

    /**
     * Test attribute "verkkopankki_id"
     */
    public function testPropertyVerkkopankkiId()
    {
    }
}
