<?php
/**
 * ViabillTransactionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.28
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Reepay;

/**
 * ViabillTransactionTest Class Doc Comment
 *
 * @category    Class
 * @description ViabillTransaction
 * @package     Reepay
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ViabillTransactionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ViabillTransaction"
     */
    public function testViabillTransaction()
    {
    }

    /**
     * Test attribute "error"
     */
    public function testPropertyError()
    {
    }

    /**
     * Test attribute "refTransaction"
     */
    public function testPropertyRefTransaction()
    {
    }

    /**
     * Test attribute "errorState"
     */
    public function testPropertyErrorState()
    {
    }

    /**
     * Test attribute "acquirerMessage"
     */
    public function testPropertyAcquirerMessage()
    {
    }

    /**
     * Test attribute "viabillId"
     */
    public function testPropertyViabillId()
    {
    }
}
