<?php
/**
 * AddonApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use \Reepay\Configuration;
use \Reepay\ApiClient;
use \Reepay\ApiException;
use \Reepay\ObjectSerializer;

/**
 * AddonApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AddonApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for createAddOn
     *
     * Create add-on.
     *
     */
    public function testCreateAddOn()
    {

    }

    /**
     * Test case for deleteAddOn
     *
     * Delete add-on.
     *
     */
    public function testDeleteAddOn()
    {

    }

    /**
     * Test case for deleteMetadata
     *
     * Delete metadata.
     *
     */
    public function testDeleteMetadata()
    {

    }

    /**
     * Test case for getAddOn
     *
     * Get add-on.
     *
     */
    public function testGetAddOn()
    {

    }

    /**
     * Test case for getAddOns
     *
     * Get list of add-ons.
     *
     */
    public function testGetAddOns()
    {

    }

    /**
     * Test case for getMetadata
     *
     * Get metadata.
     *
     */
    public function testGetMetadata()
    {

    }

    /**
     * Test case for undeleteAddOn
     *
     * Un-delete add-on.
     *
     */
    public function testUndeleteAddOn()
    {

    }

    /**
     * Test case for updateAddOn
     *
     * Update add-on.
     *
     */
    public function testUpdateAddOn()
    {

    }

    /**
     * Test case for updateMetadata
     *
     * Create or update metadata.
     *
     */
    public function testUpdateMetadata()
    {

    }

}
