<?php
/**
 * AgreementApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use \Reepay\Configuration;
use \Reepay\ApiClient;
use \Reepay\ApiException;
use \Reepay\ObjectSerializer;

/**
 * AgreementApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AgreementApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for activateMpsAgreement
     *
     * Activate mps agreement by selecting provider.
     *
     */
    public function testActivateMpsAgreement()
    {

    }

    /**
     * Test case for createApplepayAgreement
     *
     * Create ApplePay agreement.
     *
     */
    public function testCreateApplepayAgreement()
    {

    }

    /**
     * Test case for createCardGatewayAgreement
     *
     * Create card gateway agreement.
     *
     */
    public function testCreateCardGatewayAgreement()
    {

    }

    /**
     * Test case for createGooglepayAgreement
     *
     * Create GooglePay agreement.
     *
     */
    public function testCreateGooglepayAgreement()
    {

    }

    /**
     * Test case for createKlarnaAgreement
     *
     * Create Klarna agreement.
     *
     */
    public function testCreateKlarnaAgreement()
    {

    }

    /**
     * Test case for createMpoAgreement
     *
     * Create MobilePay Online agreement.
     *
     */
    public function testCreateMpoAgreement()
    {

    }

    /**
     * Test case for createMpsAgreement
     *
     * Create pending MobilePay Subscriptions agreement.
     *
     */
    public function testCreateMpsAgreement()
    {

    }

    /**
     * Test case for createPaypalAgreement
     *
     * Create PayPal agreement.
     *
     */
    public function testCreatePaypalAgreement()
    {

    }

    /**
     * Test case for createPgwAgreement
     *
     * Create payment gateway agreement.
     *
     */
    public function testCreatePgwAgreement()
    {

    }

    /**
     * Test case for createPproAgreement
     *
     * Create ppro agreement.
     *
     */
    public function testCreatePproAgreement()
    {

    }

    /**
     * Test case for createResursAgreement
     *
     * Create Resurs agreement.
     *
     */
    public function testCreateResursAgreement()
    {

    }

    /**
     * Test case for createSwishAgreement
     *
     * Create Swish agreement.
     *
     */
    public function testCreateSwishAgreement()
    {

    }

    /**
     * Test case for createViabillAgreement
     *
     * Create ViaBill agreement.
     *
     */
    public function testCreateViabillAgreement()
    {

    }

    /**
     * Test case for createVippsAgreement
     *
     * Create Vipps agreement.
     *
     */
    public function testCreateVippsAgreement()
    {

    }

    /**
     * Test case for deleteGatewayAgreement
     *
     * Delete gateway agreement.
     *
     */
    public function testDeleteGatewayAgreement()
    {

    }

    /**
     * Test case for disableGatewayAgreement
     *
     * Disable gateway agreement.
     *
     */
    public function testDisableGatewayAgreement()
    {

    }

    /**
     * Test case for enableGatewayAgreement
     *
     * Enable gateway agreement.
     *
     */
    public function testEnableGatewayAgreement()
    {

    }

    /**
     * Test case for getCardGatewayAgreements
     *
     * Get all card gateway agreements.
     *
     */
    public function testGetCardGatewayAgreements()
    {

    }

    /**
     * Test case for getGatewayAgreement
     *
     * Get gateway agreement.
     *
     */
    public function testGetGatewayAgreement()
    {

    }

    /**
     * Test case for getGatewayAgreements
     *
     * Get all agreements.
     *
     */
    public function testGetGatewayAgreements()
    {

    }

    /**
     * Test case for updateApplepayAgreement
     *
     * Update ApplePay agreement.
     *
     */
    public function testUpdateApplepayAgreement()
    {

    }

    /**
     * Test case for updateCardGatewayAgreement
     *
     * Update card gateway agreement.
     *
     */
    public function testUpdateCardGatewayAgreement()
    {

    }

    /**
     * Test case for updateGooglepayAgreement
     *
     * Update GooglePay agreement.
     *
     */
    public function testUpdateGooglepayAgreement()
    {

    }

    /**
     * Test case for updateKlarnaAgreement
     *
     * Update Klarna agreement.
     *
     */
    public function testUpdateKlarnaAgreement()
    {

    }

    /**
     * Test case for updateMpoAgreement
     *
     * Update MobilePay Online agreement.
     *
     */
    public function testUpdateMpoAgreement()
    {

    }

    /**
     * Test case for updateMpsAgreement
     *
     * Update mps agreement.
     *
     */
    public function testUpdateMpsAgreement()
    {

    }

    /**
     * Test case for updatePaypalAgreement
     *
     * Update PayPal agreement.
     *
     */
    public function testUpdatePaypalAgreement()
    {

    }

    /**
     * Test case for updatePgwAgreement
     *
     * Update pgw agreement.
     *
     */
    public function testUpdatePgwAgreement()
    {

    }

    /**
     * Test case for updatePproAgreement
     *
     * Update ppro agreement.
     *
     */
    public function testUpdatePproAgreement()
    {

    }

    /**
     * Test case for updateResursAgreement
     *
     * Update Resurs agreement.
     *
     */
    public function testUpdateResursAgreement()
    {

    }

    /**
     * Test case for updateSwishAgreement
     *
     * Update Swish agreement.
     *
     */
    public function testUpdateSwishAgreement()
    {

    }

    /**
     * Test case for updateViabillAgreement
     *
     * Update ViaBill agreement.
     *
     */
    public function testUpdateViabillAgreement()
    {

    }

    /**
     * Test case for updateVippsAgreement
     *
     * Update Vipps agreement.
     *
     */
    public function testUpdateVippsAgreement()
    {

    }

}
