<?php
/**
 * CustomerApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use \Reepay\Configuration;
use \Reepay\ApiClient;
use \Reepay\ApiException;
use \Reepay\ObjectSerializer;

/**
 * CustomerApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CustomerApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for activatePaymentMethod
     *
     * Activate payment method.
     *
     */
    public function testActivatePaymentMethod()
    {

    }

    /**
     * Test case for addCardJson
     *
     * Add card payment method.
     *
     */
    public function testAddCardJson()
    {

    }

    /**
     * Test case for cardCopy
     *
     * Copy card payment method.
     *
     */
    public function testCardCopy()
    {

    }

    /**
     * Test case for createCustomerInvoice
     *
     * Create invoice for customer.
     *
     */
    public function testCreateCustomerInvoice()
    {

    }

    /**
     * Test case for createCustomerJson
     *
     * Create customer.
     *
     */
    public function testCreateCustomerJson()
    {

    }

    /**
     * Test case for createCustomerNoteJson
     *
     * Create customer note.
     *
     */
    public function testCreateCustomerNoteJson()
    {

    }

    /**
     * Test case for deleteCustomer
     *
     * Delete customer.
     *
     */
    public function testDeleteCustomer()
    {

    }

    /**
     * Test case for deleteMetadata1
     *
     * Delete metadata.
     *
     */
    public function testDeleteMetadata1()
    {

    }

    /**
     * Test case for deletePaymentMethod
     *
     * Delete payment method.
     *
     */
    public function testDeletePaymentMethod()
    {

    }

    /**
     * Test case for getCard
     *
     * Get card.
     *
     */
    public function testGetCard()
    {

    }

    /**
     * Test case for getCardDetails
     *
     * Get gateway card details.
     *
     */
    public function testGetCardDetails()
    {

    }

    /**
     * Test case for getCustomer
     *
     * Get customer.
     *
     */
    public function testGetCustomer()
    {

    }

    /**
     * Test case for getCustomerNotes
     *
     * Get customer notes.
     *
     */
    public function testGetCustomerNotes()
    {

    }

    /**
     * Test case for getCustomerPaymentMethods
     *
     * Get payment methods.
     *
     */
    public function testGetCustomerPaymentMethods()
    {

    }

    /**
     * Test case for getCustomers
     *
     * Get list of customers.
     *
     */
    public function testGetCustomers()
    {

    }

    /**
     * Test case for getMetadata1
     *
     * Get metadata.
     *
     */
    public function testGetMetadata1()
    {

    }

    /**
     * Test case for getMpsDetails
     *
     * Get MobilePay Subscriptions agreement details.
     *
     */
    public function testGetMpsDetails()
    {

    }

    /**
     * Test case for getMpsSubscription
     *
     * Get MobilePay Subscriptions agreement.
     *
     */
    public function testGetMpsSubscription()
    {

    }

    /**
     * Test case for importCardJson
     *
     * Import card payment method.
     *
     */
    public function testImportCardJson()
    {

    }

    /**
     * Test case for inactivatePaymentMethod
     *
     * Inactivate payment method.
     *
     */
    public function testInactivatePaymentMethod()
    {

    }

    /**
     * Test case for reactivateCard
     *
     * Reactivate failed card.
     *
     */
    public function testReactivateCard()
    {

    }

    /**
     * Test case for updateCustomerJson
     *
     * Update customer.
     *
     */
    public function testUpdateCustomerJson()
    {

    }

    /**
     * Test case for updateMetadata1
     *
     * Create or update metadata.
     *
     */
    public function testUpdateMetadata1()
    {

    }

}
