<?php
/**
 * InvoiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * API
 *
 * REST API to manage Reepay resources
 *
 * OpenAPI spec version: 1
 *
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.41
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Reepay;

use Reepay\Configuration;
use Reepay\ApiException;
use Reepay\ObjectSerializer;

/**
 * InvoiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Reepay
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class InvoiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelAllDunningPending
     *
     * Cancel all dunning and pending.
     *
     */
    public function testCancelAllDunningPending()
    {
    }

    /**
     * Test case for cancelInvoice
     *
     * Cancel invoice.
     *
     */
    public function testCancelInvoice()
    {
    }

    /**
     * Test case for cancelSettleLater
     *
     * Cancel settle later.
     *
     */
    public function testCancelSettleLater()
    {
    }

    /**
     * Test case for cancelTransaction
     *
     * Cancel transaction.
     *
     */
    public function testCancelTransaction()
    {
    }

    /**
     * Test case for createOrUpdateBillingAddress
     *
     * Create or update invoice billing address.
     *
     */
    public function testCreateOrUpdateBillingAddress()
    {
    }

    /**
     * Test case for createOrUpdateShippingAddress
     *
     * Create or update invoice shipping address.
     *
     */
    public function testCreateOrUpdateShippingAddress()
    {
    }

    /**
     * Test case for deleteBillingAddress
     *
     * Delete invoice billing address.
     *
     */
    public function testDeleteBillingAddress()
    {
    }

    /**
     * Test case for deleteMetadata2
     *
     * Delete metadata.
     *
     */
    public function testDeleteMetadata2()
    {
    }

    /**
     * Test case for deleteShippingAddress
     *
     * Delete invoice shipping address.
     *
     */
    public function testDeleteShippingAddress()
    {
    }

    /**
     * Test case for detachFromSubscription
     *
     * Detach from subscription.
     *
     */
    public function testDetachFromSubscription()
    {
    }

    /**
     * Test case for extendKAuthTransaction
     *
     * Extend authorization transaction.
     *
     */
    public function testExtendKAuthTransaction()
    {
    }

    /**
     * Test case for extendKlarnaTransaction
     *
     * Extend Klarna authorization transaction.
     *
     */
    public function testExtendKlarnaTransaction()
    {
    }

    /**
     * Test case for failInvoice
     *
     * Fail invoice.
     *
     */
    public function testFailInvoice()
    {
    }

    /**
     * Test case for getInvoice
     *
     * Get invoice.
     *
     */
    public function testGetInvoice()
    {
    }

    /**
     * Test case for getMetadata2
     *
     * Get metadata.
     *
     */
    public function testGetMetadata2()
    {
    }

    /**
     * Test case for manualSettle
     *
     * Manual settle.
     *
     */
    public function testManualSettle()
    {
    }

    /**
     * Test case for reactivateInvoice
     *
     * Reactivate invoice.
     *
     */
    public function testReactivateInvoice()
    {
    }

    /**
     * Test case for settle
     *
     * Settle.
     *
     */
    public function testSettle()
    {
    }

    /**
     * Test case for transaction
     *
     * Get transaction.
     *
     */
    public function testTransaction()
    {
    }

    /**
     * Test case for transactionDetails
     *
     * Get transaction details.
     *
     */
    public function testTransactionDetails()
    {
    }

    /**
     * Test case for updateMetadata2
     *
     * Create or update metadata.
     *
     */
    public function testUpdateMetadata2()
    {
    }
}
